/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernate;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author wedad
 */
public class JFrame extends javax.swing.JFrame {
Person p = null;
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svi = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        ispis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        izmjena = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        dove = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        idretraga = new javax.swing.JTextArea();
        imer = new javax.swing.JRadioButton();
        adre = new javax.swing.JRadioButton();
        gog = new javax.swing.JRadioButton();
        doho = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imet = new javax.swing.JTextField();
        adresa = new javax.swing.JTextField();
        godine = new javax.swing.JTextField();
        dohodak = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sz = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        psz = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        svi.setBounds(new java.awt.Rectangle(400, 100, 618, 385));

        ispis.setColumns(20);
        ispis.setRows(5);
        jScrollPane1.setViewportView(ispis);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Prikazi sve zaposlene");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Prikaz svih zaposlenih");

        javax.swing.GroupLayout sviLayout = new javax.swing.GroupLayout(svi.getContentPane());
        svi.getContentPane().setLayout(sviLayout);
        sviLayout.setHorizontalGroup(
            sviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sviLayout.createSequentialGroup()
                .addGroup(sviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sviLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sviLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel7))
                    .addGroup(sviLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButton1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        sviLayout.setVerticalGroup(
            sviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sviLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        izmjena.setBounds(new java.awt.Rectangle(600, 300, 800, 584));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pretraga ID :");

        dove.setColumns(4);
        dove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doveActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Pretraga");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        idretraga.setColumns(20);
        idretraga.setRows(5);
        jScrollPane2.setViewportView(idretraga);

        buttonGroup1.add(imer);
        imer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imer.setText("Ime");
        imer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imerActionPerformed(evt);
            }
        });

        buttonGroup1.add(adre);
        adre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adre.setText("Adresa");
        adre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adreActionPerformed(evt);
            }
        });

        buttonGroup1.add(gog);
        gog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gog.setText("Godine");
        gog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gogActionPerformed(evt);
            }
        });

        buttonGroup1.add(doho);
        doho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doho.setText("Dohodak");
        doho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dohoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Novo ime :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Promjena adrese :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Promjeni godine :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Promjena dohotka :");

        imet.setColumns(8);
        imet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imetActionPerformed(evt);
            }
        });

        adresa.setColumns(8);

        godine.setColumns(8);
        godine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godineActionPerformed(evt);
            }
        });

        dohodak.setColumns(8);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Izmjeni");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Izmjena podataka o zaposlenom na osnovu ID-a");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Sta zelite izmjeniti :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("(Uposleni kojeg treba izmjeniti)");

        sz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sz.setText("Strucno zvanje");
        sz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Strucno z. :");

        javax.swing.GroupLayout izmjenaLayout = new javax.swing.GroupLayout(izmjena.getContentPane());
        izmjena.getContentPane().setLayout(izmjenaLayout);
        izmjenaLayout.setHorizontalGroup(
            izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izmjenaLayout.createSequentialGroup()
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(godine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(dohodak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psz, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton4))
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(izmjenaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel11)
                            .addGap(131, 131, 131)
                            .addComponent(dove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton3)
                            .addGap(45, 45, 45))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, izmjenaLayout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel9))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(izmjenaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(izmjenaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(imer)
                        .addGap(29, 29, 29)
                        .addComponent(gog)
                        .addGap(18, 18, 18)
                        .addComponent(adre)))
                .addGap(31, 31, 31)
                .addComponent(doho)
                .addGap(18, 18, 18)
                .addComponent(sz)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        izmjenaLayout.setVerticalGroup(
            izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izmjenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imer)
                    .addComponent(adre)
                    .addComponent(gog)
                    .addComponent(doho)
                    .addComponent(jLabel10)
                    .addComponent(sz))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(imet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(godine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(izmjenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dohodak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(psz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(21, 21, 21))
        );

        jLabel8.setText("jLabel8");

        jLabel17.setText("jLabel17");

        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 200, 0, 0));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("Novi uposlenik");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton2.setText("Svi zaposleni");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton3.setText("Izmjena podataka");
        jToggleButton3.setToolTipText("");
        jToggleButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton4.setText("Brisanje uposlenika");
        jToggleButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hibernate/add_user_26px.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hibernate/group_26px.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hibernate/services_26px.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hibernate/t.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Informacioni sistem zaposlenih");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel13)
                        .addGap(30, 30, 30)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel15)
                        .addGap(30, 30, 30)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel20)
                        .addGap(30, 30, 30)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14))
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel15))
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel20))
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
new Zaposleni().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
int opcija =  JOptionPane.showOptionDialog(null, "Prikazi", "Prikaz zaposlenika", JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE, null, new String[] { "Sve zaposlenike","Po kriterijumu"}, null);
       
       switch(opcija) {
           
           case JOptionPane.YES_OPTION:
               
               svi.show();

                 
  
           
            break;
            
           case JOptionPane.NO_OPTION:
               
                new Tabela()
              .setVisible(true);
    
           
              
            break;
           
       }        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
new Delete().setVisible(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringBuilder rezultat = new StringBuilder();
        
        List<Person> zap = new ArrayList();
               
               try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984"))
               {
                   Statement st = conn.createStatement();
                   st.executeQuery("select * from person");
                   ResultSet rs = st.getResultSet();
                   while(rs.next()){
                       
                         rezultat.append(rs.getString("idperson"));  
                           rezultat.append(" . ");  
                           rezultat.append(rs.getString("name"));  
                           rezultat.append(" | ");  
                           
                           rezultat.append(rs.getInt("age"));  
                           rezultat.append(" | ");  
                           rezultat.append(rs.getString("adress"));  
                           rezultat.append(" | ");  
                           rezultat.append(rs.getString("salary"));
                           rezultat.append(" | "); 
                           rezultat.append(rs.getString("strucnoz"));
                           rezultat.append(" | "); 
                           rezultat.append("\n"); 
                        
                   zap.add(p);
                   
                    ispis.setText(rezultat.toString());
                
                  
                              
                   }
                   
                   
                   
               }
               catch(SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex.getMessage());
               }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        izmjena.show();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         String idd = dove.getText();
         int iddd = Integer.parseInt(idd);
         
         StringBuilder rezultat = new StringBuilder();
         
        
        try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984"))
               {
                   
                  Statement st = conn.createStatement();
                  st.executeQuery("select * from person where idperson = '" + iddd + "'");
                  ResultSet rs = st.getResultSet();
                   while(rs.next()){
                       
                         rezultat.append(rs.getString("idperson"));  
                           rezultat.append(" . ");  
                           rezultat.append(rs.getString("name"));  
                           rezultat.append(" | ");  
                           
                           rezultat.append(rs.getInt("age"));  
                           rezultat.append(" | ");  
                           rezultat.append(rs.getString("adress"));  
                           rezultat.append(" | ");  
                           rezultat.append(rs.getString("salary")); 
                            rezultat.append(" | ");  
                            rezultat.append(rs.getString("strucnoz"));  
                             rezultat.append(" | "); 
                           rezultat.append("\n");
                     
                           
                              
                   }
                 idretraga.setText(rezultat.toString());
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void imerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imerActionPerformed
       
       
       adre.setEnabled(false);
       gog.setEnabled(false);
       adresa.setEnabled(false);
       godine.setEnabled(false);
       doho.setEnabled(false);
       dohodak.setEnabled(false);
               
       
       
    }//GEN-LAST:event_imerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String dan = dove.getText();
        int dann = Integer.parseInt(dan);
       
       
        
        
       
        
  
        
        if(imer.isSelected()){
            
            String name1 = imet.getText();
            
            
            try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984"))
               {
                   PreparedStatement st = conn.prepareStatement("update person set name = ? where idperson = ? ");
                   st.setString(1, name1);
                   st.setInt(2, dann);
                   st.execute();
                    
                     
                    JOptionPane.showMessageDialog(null, "Uspjesna izmjena.");
                              
                   } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
        }
         if(gog.isSelected()){
            
            String age = godine.getText();
            
            
            try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984"))
               {
                   PreparedStatement st = conn.prepareStatement("update person set age = ? where idperson = ? ");
                   st.setString(1, age);
                   st.setInt(2, dann);
                   st.execute();
                    
                     
                    JOptionPane.showMessageDialog(null, "Uspjesna izmjena.");
                              
                   } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
        }
          if(adre.isSelected()){
            
            String adre = adresa.getText();
    
            
            
            try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984"))
               {
                   PreparedStatement st = conn.prepareStatement("update person set adress = ? where idperson = ? ");
                   st.setString(1, adre);
                   st.setInt(2, dann);
                   st.execute();
                    
                     
                    JOptionPane.showMessageDialog(null, "Uspjesna izmjena.");
                              
                   } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
        }
          if(doho.isSelected()){
            
            String dohod = dohodak.getText();
           
    
            
            
            try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984"))
               {
                   PreparedStatement st = conn.prepareStatement("update person set salary = ? where idperson = ? ");
                   st.setString(1, dohod);
                   st.setInt(2, dann);
                   st.execute();
                    
                     
                    JOptionPane.showMessageDialog(null, "Uspjesna izmjena.");
                              
                   } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
        }
          if(sz.isSelected()){
          
          String b = psz.getText();
            try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/person?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC", "root", "Wedaddracic1984")){
            
            PreparedStatement st = conn.prepareStatement("Update person set strucnoz = ? where idperson = ? ");
            
            
            st.setString(1, b);
            st.setInt(2, dann);
            st.execute();
            
            JOptionPane.showMessageDialog(null, "Izmjena izvrsena!");
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            
            
            
            }
          
          
          }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void imetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imetActionPerformed

    private void godineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_godineActionPerformed

    private void gogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gogActionPerformed
imer.setEnabled(false);
adre.setEnabled(false);
doho.setEnabled(false);
imet.setEnabled(false);
adresa.setEnabled(false);
dohodak.setEnabled(false);
    }//GEN-LAST:event_gogActionPerformed

    private void adreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adreActionPerformed
        imer.setEnabled(false);
        gog.setEnabled(false);
        doho.setEnabled(false);
        imet.setEnabled(true);
        godine.setEnabled(false);
        dohodak.setEnabled(false);
        imet.setEnabled(false);
    }//GEN-LAST:event_adreActionPerformed

    private void dohoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dohoActionPerformed
        imer.setEnabled(false);
        gog.setEnabled(false);
        adre.setEnabled(false);
        imet.setEnabled(false);
        adresa.setEnabled(false);
        godine.setEnabled(false);
    }//GEN-LAST:event_dohoActionPerformed

    private void doveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doveActionPerformed

    private void szActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szActionPerformed
imer.setEnabled(false);
gog.setEnabled(false);
adre.setEnabled(false);
doho.setEnabled(false);
imet.setEnabled(false);
godine.setEnabled(false);
adresa.setEnabled(false);
dohodak.setEnabled(false);
    }//GEN-LAST:event_szActionPerformed
    
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adre;
    private javax.swing.JTextField adresa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton doho;
    private javax.swing.JTextField dohodak;
    private javax.swing.JTextField dove;
    private javax.swing.JTextField godine;
    private javax.swing.JRadioButton gog;
    private javax.swing.JTextArea idretraga;
    private javax.swing.JRadioButton imer;
    private javax.swing.JTextField imet;
    private javax.swing.JTextArea ispis;
    private javax.swing.JFrame izmjena;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField psz;
    private javax.swing.JFrame svi;
    private javax.swing.JRadioButton sz;
    // End of variables declaration//GEN-END:variables
}
